### ISSUE TITLE
ui enhancement of become a member page 

### ISSUE THREAD

**Issue by aditya-bhaumik** [Its-Aman-Yadav/Community-Site#1015]
### Describe the feature

there are 2 different colors then the whole background is blank which is not looking good i will try to fix it 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d778a242-6784-4256-a843-9a49b4f7a314)
Before
![image](https://github.com/user-attachments/assets/489e4e2a-2302-42ca-a41b-9766c23f5557)
After

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mart007King** [comment]
Do you need someone to fix this issue or what?

**Comment by aditya-bhaumik** [comment]
> Do you need someone to fix this issue or what?

No i have already completed this issue under gssoc'24
