### ISSUE TITLE
Improving the look of massage section.

### ISSUE THREAD

**Issue by Sudhish23** [Its-Aman-Yadav/Community-Site#104]
### Describe the feature

The massage section is not looking good in white colour background I can improve it.

### Add ScreenShots

![Screenshot (301)](https://github.com/Its-Aman-Yadav/Community-Site/assets/139130786/52b5cab1-b60b-4a43-a8a0-ef76b6449e01)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dilpreet0501** [comment]
Hello @Its-Aman-Yadav , I would like to improve the message section. Following is the example how I can improve the message section. Further, I will do necessary changes to fonts and style.

![Screenshot 2024-05-12 153704](https://github.com/Its-Aman-Yadav/Community-Site/assets/100590445/2c48acb6-af0f-4e87-b53d-fde3375400b2)

Kindly assign this issue to me under GSSoC'24, I will do my best!

Checklist
 
- [ ] I agree to follow this project's Code of Conduct
- [ ]  I'm a GSSOC'24 contributor
- [ ]  I want to work on this issue
