### ISSUE TITLE
Feat: Providing a Nav bar to the page

### ISSUE THREAD

**Issue by Divyanshu832** [Its-Aman-Yadav/Community-Site#107]
### Describe the feature

Adding a  Nav bar to the section would surely give the page a better look. Moreover users would find it very easy to get to the required sections. They can easily get to cards or contact form and our page would look more professional

### Add ScreenShots

![Screenshot 2024-05-11 230604](https://github.com/Its-Aman-Yadav/Community-Site/assets/149070310/2599e05e-3958-43d1-8cb2-e1088130d610)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Please assign me this !

**Comment by Aleena-Memon** [comment]
please , assign me this issue , so i can work on it under GSSOC24

**Comment by eatulrajput** [comment]
Hi, I would like to work on this

**Comment by Its-Aman-Yadav** [comment]
Duplicate issue

**Comment by Divyanshu832** [comment]
Sorry I didn't get it, Should I work on this issue with other issue or should I recreate it?
