### ISSUE TITLE
Feat: add dark mode feature in mentorship page 

### ISSUE THREAD

**Issue by ANKeshri** [Its-Aman-Yadav/Community-Site#1105]
### Describe the feature

dark mode is not available in mentorship page 

### Add ScreenShots

before : 

https://github.com/user-attachments/assets/a9cfd4b9-cbb0-44a3-a2dd-9ccc361fcdbf

after : 

https://github.com/user-attachments/assets/a586123e-18cf-4f10-81ad-a4210d4a7f51

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Deepak2047** [comment]
I would like to work on this Project .Please assign to me.
