### ISSUE TITLE
Add Icons to Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [Its-Aman-Yadav/Community-Site#1251]
### Describe the feature

Hello Project Admin
I would like to add icons to Footer
Can you assign me this issue under GSSOC'24 

### Add ScreenShots

![IMG_20240727_121041](https://github.com/user-attachments/assets/074d7246-74fe-48c3-986d-e53baf193ec9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @Kalivarapubindusree @Its-Aman-Yadav

**Comment by Kalivarapubindusree** [comment]
Sailaja may I know where u want to add icons ? @sailaja-adapa

**Comment by sailaja-adapa** [comment]
Noo @Kalivarapubindusree see once in footer

**Comment by Kalivarapubindusree** [comment]
May I know what r the icons u want to add in the footer @sailaja-adapa

**Comment by sailaja-adapa** [comment]
@Kalivarapubindusree I will add Icons to all links like serives,links and legals ones

**Comment by SaanyaGarg5** [comment]
I would like to work on this..
assign that task to me

**Comment by developersandeepji** [comment]
Hi! I would like to work on this issue. Can you please assign it to me?

**Comment by sandeepmaurya0786** [comment]
Hi! I would like to work on this issue. Can you please assign it to me?
