### ISSUE TITLE
In Contact Us adding a pop-up message when the details are submitted.

### ISSUE THREAD

**Issue by Vaishnavigunti2801** [Its-Aman-Yadav/Community-Site#1253]
### Describe the feature

Hello PA,
In contact Us page we don't know whether form submitted or not So I will add a pop-up message when the click on submit button a pop-up message will display .

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a4d6e74b-5e19-479a-bb8e-f6d4157202b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanjanadas45** [comment]
Please assign me this.
