### ISSUE TITLE
Feat: Improve the slideshow of images.

### ISSUE THREAD

**Issue by DevNandini02** [Its-Aman-Yadav/Community-Site#128]
### Describe the feature

For a good using experience, more images should be added to the slideshow. There are only 2 images at present. Add more images , also transition speed between the images should be slow.

### Add ScreenShots

https://github.com/Its-Aman-Yadav/Community-Site/assets/124669890/3621a99b-9072-42ac-a500-7291e82268cd

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevNandini02** [comment]
@Its-Aman-Yadav sir please assign this to me. I want to work on this.

**Comment by Its-Aman-Yadav** [comment]
Sure, please work on it @DevNandini02

**Comment by SadiyaTahsin29** [comment]
I request that you assign me the following task.

**Comment by DevNandini02** [comment]
> Sure, please work on it @DevNandini02 
@Its-Aman-Yadav sir i have updated it and sent the pull request.
