### ISSUE TITLE
BUG: Unresponsve page when visiting navbar menu links

### ISSUE THREAD

**Issue by techy4shri** [Its-Aman-Yadav/Community-Site#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar menu link for testimonials, when clicked, takes us to the section but makes the page unresponsive.
You can do nothing on there, no clicks, hover nothing. It seems the error happens only when the link takes you to a section of the home page, when visiting a completely different page, no issue is there.
To check:
1. Go to the website
2. Click on either Reviews or Services in navbar menu.
3.  Visit the section and see error.
![Screenshot 2024-07-29 132117](https://github.com/user-attachments/assets/f7a0833e-978b-483a-9322-bc2e22df6916)
![image](https://github.com/user-attachments/assets/a9bc7c00-e0e1-40fd-82ad-70289a1c0ed4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by techy4shri** [comment]
@Its-Aman-Yadav kindly assign this issue to me.

**Comment by Kalivarapubindusree** [comment]
It's is working for me dear please check once again
