### ISSUE TITLE
Feat: Feedback Form Issue

### ISSUE THREAD

**Issue by TBorundia** [Its-Aman-Yadav/Community-Site#1282]
### Describe the feature

Form is taking empty input too, so adding validation.
Improving UI to match website theme.
Page is not responsive to all screen size

### Add ScreenShots

![image](https://github.com/user-attachments/assets/79ff86ee-3932-4ae2-b5fe-e96cc50cc187)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@Its-Aman-Yadav  @Kalivarapubindusree ,
Please assign this issue to me under GSSoC'24. Thank You!

**Comment by Kalivarapubindusree** [comment]
Make it responsive and align the sections so that good UX in any screen size.
