### ISSUE TITLE
Spam: Either Block user or ban on the repo

### ISSUE THREAD

**Issue by sanjay-kv** [Its-Aman-Yadav/Community-Site#1283]
![image](https://github.com/user-attachments/assets/e8f6304b-0e5f-4b02-a67a-c0f47ff2acf8)
all are minor nav bar fix assigned level 3

It has been noticed this repo is not following any guidelines, We will be either banning a user who got irrelevant labels or the complete repo. 
I have requested the invitation to manage labels. we cant publish the results with this much spams on the leaderboard

**Comment by sau-mili** [comment]
hey, I see some these are my PRs. I haven't requested labels. For minor issues, shouldn't I get level 1s or level2s instead of direct ban. I don't see my fault here.

**Comment by sanjay-kv** [comment]
@Kalivarapubindusree 

i still dont have access to this repo and its unfortunate that you guys has admin didn't take any actions, I'm blocking this repo on this program.

**Comment by Kalivarapubindusree** [comment]
Can you please send the pr links here
