### ISSUE TITLE
feat🌟: Adding Diagonal-Transitional Effect to "Each Contributors Card"

### ISSUE THREAD

**Issue by aslams2020** [Its-Aman-Yadav/Community-Site#1287]
### Describe the feature

Hey @Its-Aman-Yadav and @Kalivarapubindusree 

I want to suggest a new feature for "Contributors" Page.

I Want **to add a "Diagonal-Transitional" Effect Styling to each card** of the Contributors page. 
Which means On hovering on Every card, The card will display a Transitional Effect

**For ex.  Like this -(I will follow the website theme)** 

https://github.com/user-attachments/assets/b70c3c22-fc3f-4397-854f-53a413bf4d60

**Current Contributor Cards -** 

https://github.com/user-attachments/assets/b5ee3b60-1d72-47a3-9e77-ebd4d2d842b8

As you can see, currently the hovering effects are lagging and have no smooth hover effect.

Please Assign me this issue

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@Kalivarapubindusree @Its-Aman-Yadav  i want to work on this. 
please assign me.

**Comment by Kalivarapubindusree** [comment]
Yeah that was nice please go on @aslams2020
