### ISSUE TITLE
Feat:More features

### ISSUE THREAD

**Issue by sharmi4590** [Its-Aman-Yadav/Community-Site#131]
### Describe the feature
Hey @Its-Aman-Yadav 
We can use discord and linkedin icons on the front page to make it more clear  because a button for a particular site without its icon will not look good and navbar should be added as well as the footer is so bland we can add other features in the footer as well and you can also add testimonials.

### Add ScreenShots

![Screenshot (362)](https://github.com/Its-Aman-Yadav/Community-Site/assets/102676949/16ad24da-8c63-4f60-86fc-aad9bb7f71a9)
Like these buttons ocourse more related to your website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SanaAzeem512** [comment]
@please assign this issue to me

**Comment by Its-Aman-Yadav** [comment]
Could you please just add logo to the existing button with transparent bg and white color? @sharmi4590

**Comment by sharmi4590** [comment]
@Its-Aman-Yadav Yes I will add it like that only.

**Comment by sharmi4590** [comment]
@Its-Aman-Yadav Please assign it to me to complete the task.
