### ISSUE TITLE
Feat: Make contact form working

### ISSUE THREAD

**Issue by zalabhavy** [Its-Aman-Yadav/Community-Site#1318]
### Describe the feature

I will make contact form working after sumbit.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Kalivarapubindusree @Its-Aman-Yadav Please assign me this task !

Thank You !

**Comment by Kalivarapubindusree** [comment]
Can you please explain ur issue in brief @zalabhavy

**Comment by zalabhavy** [comment]
@Kalivarapubindusree 
![image](https://github.com/user-attachments/assets/b7252889-4015-43c1-b991-32f42302f9ac)

In this form when i submit page is reload and not show any message so i want to show thank you message prevent from reload and reset form after submition.
