### ISSUE TITLE
BUG:hover issue 

### ISSUE THREAD

**Issue by Varsani2520** [Its-Aman-Yadav/Community-Site#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when i hover on the icon buttons then it is not display perfectly ,
i think we should to change some :
![image](https://github.com/user-attachments/assets/5b3d9e54-3456-48aa-a110-61e3c7d9dcea)
![image](https://github.com/user-attachments/assets/6cb406f9-49e4-4fab-acb3-eda6e91a9792)
 in this route :`https://community-site-theta.vercel.app/profile.html#settings`

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@Its-Aman-Yadav ,assign me

**Comment by BhavikaPachauri** [comment]
@Its-Aman-Yadav  I want to work on this issue
