### ISSUE TITLE
To change the `placeholder` colour

### ISSUE THREAD

**Issue by vaishnavi-agr** [Its-Aman-Yadav/Community-Site#1402]
### Describe the feature

The placeholder coloue of the input feild matches with the backend image which looks inconvienient and even the user might not able to see it.

### Add ScreenShots

![Screenshot 2024-08-10 205950](https://github.com/user-attachments/assets/4f737973-b960-483e-bfdb-90029d34ce0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MrinmayiVerma** [comment]
I would want to work on this issue, could you assign it to me

**Comment by SaanyaGarg5** [comment]
i like to work on this..
you can assign this task to me

**Comment by SohamDas00** [comment]
please assign me this issue
