### ISSUE TITLE
Feat: Centering the Get In Touch card in the Contact Us Container

### ISSUE THREAD

**Issue by Shahid6174** [Its-Aman-Yadav/Community-Site#1408]
### Describe the feature

The problem here is the card seems to be cut-out from the container and the placeholder text differs in the message input field.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2e8b5754-7f9b-4581-8c17-42a5b4ed23cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SohamDas00** [comment]
assign me please
