### ISSUE TITLE
BUG: the cards with refresh, pc, and message logo are not responsive

### ISSUE THREAD

**Issue by arpan2233** [Its-Aman-Yadav/Community-Site#142]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Here is the pic of the issue
PLease assign this task to me
![iconsresponsive](https://github.com/Its-Aman-Yadav/Community-Site/assets/118041697/afe1f82f-d7cc-475f-a4b2-23876bfcdd7b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Sure, please work on it

**Comment by Prashant-2024** [comment]
I would like to work on this issue, please assign it to me under GSSOC'24.

**Comment by arpan2233** [comment]
@Prashant-2024 I made some changes, also my pull request has been merged 
I forgot to close it, if you want to work further on it pls mention or else I'll close this issue

**Comment by Prashant-2024** [comment]
You can close this issue
