### ISSUE TITLE
Feat: Change the old logo of twitter to X

### ISSUE THREAD

**Issue by ratna-jaiswal** [Its-Aman-Yadav/Community-Site#1466]
### Describe the feature

In contact us and profile section the logo of twitter is older version i want to update it with the newer version X

Pls assign this issue to me

I am gssoc-extd and hactoberfest contributor so pls assign thhe label also

### Add ScreenShots

![Screenshot (1163)](https://github.com/user-attachments/assets/b84bc9e2-5188-4ac9-bffa-8dae45648e56)
![Screenshot (1162)](https://github.com/user-attachments/assets/52f4229a-78e8-46a8-8eae-fcba5566658a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SohamDas00** [comment]
assign me this issue
