### ISSUE TITLE
BUG: Add Hovering effect

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Its-Aman-Yadav/Community-Site#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Adding hovering effect to the page make it attractive and impressive..

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuhainaFathimaM** [comment]
@Its-Aman-Yadav I want to hovering effect of the website .. it can be improved. 
@Its-Aman-Yadav I want to contribute to this project. So please assign this issue to me. 
I have worked on many open source projects

**Comment by Nih1tGupta** [comment]
I want to contribute to this project. So please assign this issue to me.

**Comment by Its-Aman-Yadav** [comment]
Hey @SuhainaFathimaM please work on it, waiting for your PR

**Comment by SuhainaFathimaM** [comment]
#231  Resolves this issue

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.
