### ISSUE TITLE
BUG: Improve UI and add fields to Contact Form

### ISSUE THREAD

**Issue by aartijangra** [Its-Aman-Yadav/Community-Site#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would like to contribute to the project by improving the user interface (UI) of the "Get in Touch" contact form and adding more input fields to enhance its functionality. The current UI of the form is not visually appealing, and it lacks certain fields that could provide a better user experience.
I propose to work on the following improvements:
~Redesign the UI of the contact form to make it more visually appealing and user-friendly.
~Enhance the styling of the form elements, such as input fields and buttons, to create a consistent and professional look.
~Add more input fields to the form, such as address, contact number to allow users to specify the purpose of their message.
~Improve the layout and spacing of the form elements to make it easier for users to fill out the form.
~Ensure that the form is responsive and works well on various devices and screen sizes.
By implementing these improvements, the contact form will have a better UI and provide a more comprehensive way for users to get in touch with the project. I am confident in my ability to make these changes and contribute to the overall quality of the project.
Please assign me this issue so that I can start working on it. If you have any specific requirements or guidelines, please let me know, and I will be happy to follow them. @Its-Aman-Yadav 
![Screenshot 2024-05-13 001434](https://github.com/Its-Aman-Yadav/Community-Site/assets/143300846/127ee5dd-89c2-4c8c-b9b9-e919fa1cd918)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nih1tGupta** [comment]
Willing to work on this issue under GSSOC'24. Please assign this issue to me
