### ISSUE TITLE
Login and signup

### ISSUE THREAD

**Issue by Vishnu1804K** [Its-Aman-Yadav/Community-Site#17]
since your platform is aiming for the community building so I want to create a login and signin page first so that  user can login and signup into your platform so that after wards we can implement new features please assign me this feature under GSSOC'24

**Comment by Its-Aman-Yadav** [comment]
Your idea is good @Vishnu1804K but I don't think so every person wants to make his account, and what will be shown to person if he logged in? 

We are just presenting them the link of our discord server that's it

**Comment by Vishnu1804K** [comment]
but it will be too clumsy for the people for the users to handle

**Comment by Vishnu1804K** [comment]
why i am telling login and signup means because related to backend we can implemt new feature in your website dynamically

**Comment by Its-Aman-Yadav** [comment]
I don't see any benefits of implementing this feature as of now, please raise another meaningful issue
