### ISSUE TITLE
Copyright symbol missing in the Footer

### ISSUE THREAD

**Issue by Ajita369** [Its-Aman-Yadav/Community-Site#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is always a copyright symbol near "Copyright" text in the websites which is missing here.
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/162597493/d6ed0c41-53b8-4a79-a99d-0177c5aee42d)
I want you to assign this issue to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.
