### ISSUE TITLE
Feat: Adding a stunning and stunning logo to the website

### ISSUE THREAD

**Issue by meghana9044** [Its-Aman-Yadav/Community-Site#175]
### Describe the feature

@Its-Aman-Yadav I'm interested in contributing to this project by creating and adding a very good logo to the website under GSSOC'24. Logo is very important for any website. 

### Add ScreenShots

I will be creating and adding a beautiful logo to this website. I'm very good at canva. Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Hey @meghana9044 currently we don't need any logo
Thank you
