### ISSUE TITLE
BUG:  URGENT LOOK INTO MERGED PRs AGAINNNN 

### ISSUE THREAD

**Issue by kairveeehh** [Its-Aman-Yadav/Community-Site#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

THE whole site is changed again in the live links as well as the deployed version cards are gone testimoniakls look bad and lot of damage 
## please see it asap
@Its-Aman-Yadav  @Its-Aman-Yadav  @Its-Aman-Yadav  noticed it while deleting those small mistakes 
also it shows my footer to be already there have you merged it already????
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ankur-Rai-19** [comment]
Please approve the pull request after reviewing the code. The changes made to the live website were significantly different.
