### ISSUE TITLE
BUG: Footer isn't responsive

### ISSUE THREAD

**Issue by AlaynaShaheen** [Its-Aman-Yadav/Community-Site#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As we can see, footer is not responsive in the mobile view and also the bullet points added doesn't look good. A screenshot of which I have attached below. 
![Screenshot 2024-05-13 220933](https://github.com/Its-Aman-Yadav/Community-Site/assets/111679498/73849270-5a83-4463-9302-ada484ea4fc2)
We can make it responsive by adding necessary CSS styles to the website.

@Its-Aman-Yadav I am a contributor under GSSoC'24. I can resolve this issue. So please assign this to me.
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Its-Aman-Yadav** [comment]
yeah @AlaynaShaheen kindly work on it
