### ISSUE TITLE
Feat: Adding a navbar on top

### ISSUE THREAD

**Issue by souvik-maity** [Its-Aman-Yadav/Community-Site#204]
### Describe the feature

We can add a navbar consisting of home, about us, contact us and support elements

### Add ScreenShots

![Screenshot 2024-05-14 215122](https://github.com/Its-Aman-Yadav/Community-Site/assets/145227417/cc84fe67-25f5-417f-9a4c-56e5e870e927)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souvik-maity** [comment]
kindly consider assigning it to me.

**Comment by Its-Aman-Yadav** [comment]
Duplicate issue
