### ISSUE TITLE
Feat: Adding a FAQ section can enhance the website

### ISSUE THREAD

**Issue by souvik-maity** [Its-Aman-Yadav/Community-Site#206]
### Describe the feature

adding an accordion for the FAQ section can make the website better

### Add ScreenShots

![Screenshot 2024-05-14 215424](https://github.com/Its-Aman-Yadav/Community-Site/assets/145227417/133589cd-cd50-4ca9-8432-7504a00ba183)
FAQ to be added before the footer

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souvik-maity** [comment]
kindly assign it to me

**Comment by Its-Aman-Yadav** [comment]
Duplicate issue
