### ISSUE TITLE
Spelling errors 

### ISSUE THREAD

**Issue by Ajita369** [Its-Aman-Yadav/Community-Site#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are many spelling errors on this page as shown in the screenshot below :
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/162597493/79afd24a-9b21-4e2b-95de-14b293b82414)
I can fix this issue so please assign this issue to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
please work on it @Ajita369

**Comment by nileshsn** [comment]
Please assign it to me @Its-Aman-Yadav

**Comment by Ishmeetkaur36** [comment]
I would like to look into this issue

**Comment by Its-Aman-Yadav** [comment]
This issue is closed
