### ISSUE TITLE
DOC: Flex boxs and Footer

### ISSUE THREAD

**Issue by nileshsn** [Its-Aman-Yadav/Community-Site#219]
### What's wrong with the existing documentation

1. On the website, we can observe that on the 3rd page, the flex items are not aligned perfectly, and the hover effect is not working properly. When hovering, the text does not fit on the screen and zooms in too much.

2. The list items in the footer are not aligned correctly, and the list symbols are not hidden.

### Add ScreenShots

![Screenshot_20240515_091259](https://github.com/Its-Aman-Yadav/Community-Site/assets/87946769/50ba6c9a-3001-4fdf-8353-cf492c0261c4)
223f-73ca-404e-963e-ab6069dee19b)
![Screenshot_20240515_091254](https://github.com/Its-Aman-Yadav/Community-Site/assets/87946769/ca93b89b-3ad1-47de-ae99-4f3951b02a0e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Sure, please work on it @nileshsn

**Comment by kaushik-2318** [comment]
I Can also do that.
# Please assign this issue to me so that I can start working over it

**Comment by nileshsn** [comment]
I successfully resolved the issues I was assigned to, Thank you @Its-Aman-Yadav 
![Screenshot (224)](https://github.com/Its-Aman-Yadav/Community-Site/assets/87946769/d0294efa-e1b9-45b7-bf28-9ab6b0938fe1)
![Screenshot (225)](https://github.com/Its-Aman-Yadav/Community-Site/assets/87946769/d0b7fdac-3c69-469f-aae6-fa67ca86a0ef)
![Screenshot (226)](https://github.com/Its-Aman-Yadav/Community-Site/assets/87946769/1adf867c-e629-42a3-ab94-bd0d2fb511e5)

**Comment by kaushik-2318** [comment]
Footer is not align properly I can do that.

# Please assign this issue to me so that I can start working over it
