### ISSUE TITLE
Enhancement of CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by syrnxalno** [Its-Aman-Yadav/Community-Site#22]
The CODE_OF_CONDUCT.md file appears to lack visual appeal and may benefit from enhancements to improve its aesthetic appeal and readability. I would like to increase the clarity of information displayed, especially in the attribution section. Besides this, there also seems to be a a contact information issue in the 'Enforcement' section which can be rectified as well.
![Screenshot (196)](https://github.com/Its-Aman-Yadav/Community-Site/assets/150210401/311ce8e2-56b5-47d2-b2fe-ebba19aef508)

I request you to assign this enhancement to me.

**Comment by Its-Aman-Yadav** [comment]
Please add some visuals to this and raise a PR @syrnxalno

**Comment by syrnxalno** [comment]
Sure @Its-Aman-Yadav, I can do that. Can I raise the PR after 7 PM today though? There was an announcement that said contributions made after 7 PM today are the only ones counted for the leaderboard. I will ensure the PR is made by the end of day.

Thank you for considering this!
