### ISSUE TITLE
Social Media links in the footer are not working!!

### ISSUE THREAD

**Issue by UjjwalGupta1105** [Its-Aman-Yadav/Community-Site#226]
### Describe the feature

Social Media links in the footer are not working .I want to add the respective links .

### Add ScreenShots

![links10](https://github.com/Its-Aman-Yadav/Community-Site/assets/165131091/f95d8619-c3af-4246-881e-89544b19725b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mahimatestgithub** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by yash5080** [comment]
assign me this issue

**Comment by kashisharora9462** [comment]
I would like to contribute by activating these links and enhancing their appearance to be more appealing and user-friendly.

**Comment by princyym** [comment]
I would like to work on this issue, Could you please provide me the links of the Instagram, Facebook and Twitter. @Its-Aman-Yadav
