### ISSUE TITLE
Feedback button in the navigation bar does not work

### ISSUE THREAD

**Issue by SrujanV010** [Its-Aman-Yadav/Community-Site#234]
### What's wrong with the existing documentation

The feedback section in the navigation bar doesn't work and i would like to add a feedback section for the website and on clicking the feedback button navigates the user to this section. Please assign this issue to me.

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/137309655/194cd11d-cc6b-4722-861b-60ffc53b6261)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by niteshbca** [comment]
@SrujanV010 i want to work on this issue please assgin me.
