### ISSUE TITLE
Addition of Project name beside the icon and of the review(testimonial) section to the navbar.

### ISSUE THREAD

**Issue by Nayanika1402** [Its-Aman-Yadav/Community-Site#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The testimonial section rather the review section is not mentioned in the navbar.I want to link the testimonial part to the newly added feature in the navbar and also add the project name in the navbar beside the project icon.Kindly assign me the issue @Its-Aman-Yadav .
Existing Navbar:
![Screenshot 2024-05-15 210953](https://github.com/Its-Aman-Yadav/Community-Site/assets/132455412/878e2768-0ccd-4fa3-aeb6-a37be0ce84b6)
Somwthing like this:
![Screenshot 2024-05-12 205631](https://github.com/Its-Aman-Yadav/Community-Site/assets/132455412/6c6125a3-917c-4c95-b34f-5943798b8637)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Yeah sure @Nayanika1402 please work on it

**Comment by kashisharora9462** [comment]
I can add it and will add in a nicer way so that it looks nice.Please give a chance to me to do so
