### ISSUE TITLE
Feat: Adding Rounding Radius To Get In Touch Send Button

### ISSUE THREAD

**Issue by Siddhant-Mahato** [Its-Aman-Yadav/Community-Site#245]
### Describe the feature

The Get In Touch Button will looking more appealing if will make the Send Button Having Some Rounding Radius , so can make it.

### Add ScreenShots

![Screenshot (632)](https://github.com/Its-Aman-Yadav/Community-Site/assets/127202564/6c22a699-4f7c-4117-87cc-99540556a207)

Will Make it to have some rounding radius.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Mahato** [comment]
Hello @Its-Aman-Yadav  Can You Please assign me this issue and Please add sort of Level to the Issue.

**Comment by Its-Aman-Yadav** [comment]
Could you provide a sample of it?

**Comment by Siddhant-Mahato** [comment]
Yeah Sure like if i am going to make GET IN TOUCH BUTTON like the below PIC , then will look more appealing 

![Screenshot (633)](https://github.com/Its-Aman-Yadav/Community-Site/assets/127202564/de3488ca-4911-4879-b5f6-b709f6597f75)

**Comment by Siddhant-Mahato** [comment]
If it is looking good to you @Its-Aman-Yadav  , then please add a level to the issue and assign me to do the PR , Please .

**Comment by Its-Aman-Yadav** [comment]
Hmm looking nice, please work on it

**Comment by Siddhant-Mahato** [comment]
Hello @Its-Aman-Yadav  , I have done the required changes so it should look appealing on all type of screen set , please check it and Merge the issue . Thank You 😊

**Comment by souvik-maity** [comment]
@Its-Aman-Yadav I have also raised a pull request addressing the same issue. Along with adding border-radius i have also removed the unnecessary extra padding which made the button look extremely big. You can check the PR .Thanks.
