### ISSUE TITLE
Adding icons on the  navbar

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Its-Aman-Yadav/Community-Site#247]
### Describe the feature

adding different icons on the navbar would make it look more efficient.
@Its-Aman-Yadav kindly assign me this issue under gssoc'24.

### Add ScreenShots

![Screenshot 2024-05-15 002803](https://github.com/Its-Aman-Yadav/Community-Site/assets/117037441/79fbf149-289b-4a58-99b9-7426d62ed1e3)
somewhat like this for different icons

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souvik-maity** [comment]
I really want to contribute on this .Kindly assign this to me.
