### ISSUE TITLE
Feat: Improve the UI and UX for the Home Buttons

### ISSUE THREAD

**Issue by Sheryar-bit** [Its-Aman-Yadav/Community-Site#249]
### Describe the feature

I want to improve the styling and would like to add effects on the home buttons 
Please assign this issue to me @Its-Aman-Yadav 

### Add ScreenShots

Before:
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/132276541/da15e10e-8366-407d-bc0d-9735bca8dba8)

After:
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/132276541/6e250442-07f1-4a9c-96a6-319a4c58391e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Thank you
