### ISSUE TITLE
Create more information in the form section, just like ph number etc

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Its-Aman-Yadav/Community-Site#25]
Hello, @Its-Aman-Yadav 
Please assign this issue to me....I want to add more things in the form section
#GSSoC'24

**Comment by Justaditi** [comment]
Please assign me this issue I have knowledge about this section

**Comment by Hemav009** [comment]
Hi @Its-Aman-Yadav 

Please assign me this issue I would like to add more things in the form section like phone number, skills, etc.

**Comment by YazhiniVenkatesan12** [comment]
HI @Its-Aman-Yadav 

Hi, I'm Yazhini , a participant in GSSoC24. I would like to contribute to this project. I have experience with HTML ,CSS ,JAVASCRIPT, and I'm interested  to add more things in the form section like phone number, etc. . May I be assigned with this issue?

Thank you!

**Comment by Its-Aman-Yadav** [comment]
it is not necessary, thank you for addressing
