### ISSUE TITLE
Feat: Review Page

### ISSUE THREAD

**Issue by kanishka-parmar** [Its-Aman-Yadav/Community-Site#252]
### Describe the feature

We can add a review page where the individuals who are part of the community can tell how it helped them and why should one become a part of this community.
Review page will contain insights of the participants of the community.

### Add ScreenShots

Something like this.

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/114792553/cdb701f1-7cad-4e5e-8122-0deb348ae24d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
But we have testimonials section for it

**Comment by kanishka-parmar** [comment]
@Its-Aman-Yadav yeah I don't know but when I saw the review heading was not there in navigation bar so I missed that part I think sorry I will look for some other issue.

**Comment by Its-Aman-Yadav** [comment]
Thank you @kanishka-parmar
