### ISSUE TITLE
Feat: Adding transition effect to back to top button

### ISSUE THREAD

**Issue by Saimanjari777** [Its-Aman-Yadav/Community-Site#256]
### Describe the feature

There is no transition effect for back to top button. It would look good if there a transition present.
Please assign this issue to me @Its-Aman-Yadav  

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/130165687/76bdafdf-d8b2-41d9-9f2b-56ee6e500d63)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Sure please work on it @Saimanjari777

**Comment by kashisharora9462** [comment]
I can work on adding a transition effect to enhance its appearance and ensure it remains user-friendly.

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by bhaavvya** [comment]
Well @Siddhi561 & @kashisharora9462 I appreciate your enthusiasm but this issue is already assigned.

**Comment by kashisharora9462** [comment]
Thank you for your response.
