### ISSUE TITLE
Feat:Beautify Main Page

### ISSUE THREAD

**Issue by kashisharora9462** [Its-Aman-Yadav/Community-Site#269]
### Describe the feature

The "Join Us on Discord" and "LinkedIn" options do not look appealing because their box sizes are unequal, and the font family is unsuitable. Additionally, the "HELLO VILLAGE" text is partially hidden due to the image and misaligned text colour. I can improve the design to make it more attractive and user-friendly by equalizing the box sizes, choosing a better font family, and adjusting the text colour and background. I can also add a smooth animation effect to enhance the overall appearance. Please assign me this task.

![Screenshot 2024-05-17 082039](https://github.com/Its-Aman-Yadav/Community-Site/assets/153215875/4233477d-189e-404e-a0c0-e72c8ff0351c)

Please give a chance to me.

![Screenshot 2024-05-17 082039](https://github.com/Its-Aman-Yadav/Community-Site/assets/153215875/03b1f71e-cc85-4487-9fa6-d6cb32771359)
I can make it visually appealing.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PavanKumarNaik936** [comment]
**@Its-Aman-Yadav** ,can you please assign this to me , I can enhance the hime page by adjusting the font and animations when we hover the cursor over discord and linkedin boxes

**Comment by prachisah1** [comment]
Please assign me this task under GSSOC 24
I want to work on the UI and enhance the features to eye-catching features.

**Comment by kashisharora9462** [comment]
I have enhanced the styling of the links (LinkedIn and Discord) to make
them more visually appealing. Initially, only the names of the links are
displayed to the user. When the user hovers over a link, the name of the
link (e.g., LinkedIn) along with its logo is shown, and the background
colour changes. I have also added a smooth transition effect to ensure
these changes occur seamlessly. Additionally, I have updated the font
family of the headings and adjusted the colour theme to harmonize with the
background.I have tried my best to improve the overall design. If you have
any further changes or suggestions, please let me know. I kindly request
you to merge these updates into the repository to enhance its visual appeal.
