### ISSUE TITLE
Readme.md DOC can be more fascinating

### ISSUE THREAD

**Issue by Meetjain1** [Its-Aman-Yadav/Community-Site#275]
### What's wrong with the existing documentation

Readme.md file can be more fascinating by adding contributors section , missing icons of discord , linkedin and a working video of our project and by removing some irregular allignment and spacing.
@Its-Aman-Yadav sir assign this issue to me i will add it. Thankyou

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Paavni-Goyal** [comment]
Can you please assign this issue to me?

**Comment by Akshitha28112004** [comment]
Hey, I've updated the readme file for another project. You are free to check it out in my profile and please assign me this issue under gssoc'24.

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav

**Comment by Meetjain1** [comment]
@Its-Aman-Yadav let me know

**Comment by Aditi-Gopinath** [comment]
Kindly assign me this under GSSoC'24. I would like to work on it @Its-Aman-Yadav
