### ISSUE TITLE
Feat: floating navbar button

### ISSUE THREAD

**Issue by DesignDread** [Its-Aman-Yadav/Community-Site#293]
### Describe the feature

when screen size minimize from desktop to mobile instead of keeping nav bar at top we can create a floating navbar button on bottom left so that it would have a better UI

### Add ScreenShots

![Screenshot 2024-05-18 135222](https://github.com/Its-Aman-Yadav/Community-Site/assets/147525844/972bd9c2-5c6e-4ba7-9ab6-5ffc8a0af755)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
I want to work on this can you please assign it to me under gssoc label @Its-Aman-Yadav ?

**Comment by Its-Aman-Yadav** [comment]
Hey @DesignDread can you provide me a screenshot or sample for that?

**Comment by DesignDread** [comment]
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/147525844/66268f09-b53d-4cc4-b137-76bf544ce4ee)


here i created a sample using figma hope you find this well

**Comment by Its-Aman-Yadav** [comment]
But navbar should be at the top of the website. don't you think? @DesignDread

**Comment by DesignDread** [comment]
Most of the popular websites keeps their nav bar at the bottom like instagram , LinkedIn, so this floating nav bar would make the website a little diffrent and creative like if we click over it it will pop up the content drawer from its position

**Comment by Its-Aman-Yadav** [comment]
It's not a good idea ig, so I am closing this issue
