### ISSUE TITLE
DOC: want to add discord and linkin icons instead of links

### ISSUE THREAD

**Issue by Sibam-Paul** [Its-Aman-Yadav/Community-Site#294]
### Add ScreenShots

![Screenshot_20240518-150422_Chrome](https://github.com/Its-Aman-Yadav/Community-Site/assets/158052549/6545d597-8153-4ea2-9cd9-d1490234ad83)

Charging the links to icons for better visual

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sibam-Paul** [comment]
Please assign me this so that I can work on it under Gssoc'24

**Comment by Its-Aman-Yadav** [comment]
Sure add these @Sibam-Paul

**Comment by roushanverma23** [comment]
@Its-Aman-Yadav i want to work on this please assign me this work

**Comment by sakshiSakshi77** [comment]
@Its-Aman-Yadav i want to work upon this , please assign me this issue

**Comment by Paavni-Goyal** [comment]
@Its-Aman-Yadav i want to work on this please assign me this work

**Comment by nidhirajpoot** [comment]
i want to work on this please assign me this work

**Comment by nidhirajpoot** [comment]
@Its-Aman-Yadav please assign me this work i want to work on it
