### ISSUE TITLE
[BUG]: Improper alignment in Footer section

### ISSUE THREAD

**Issue by darshjnn** [Its-Aman-Yadav/Community-Site#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Improper Alignment of Footer Section**

Alignment in the footer section in not proper, giving the website an unprofessional and weird look.
Also, the font-size is very small.

### **At Current**
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/144017031/508018ef-dfc5-4c98-8952-3b0d74c1a223)

### **After Modification**
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/144017031/1c8e2a2e-48d2-4be4-879e-adcb1fdfc7d6)

### **Changes made**

1. Fixed alignment in Footer to give a professional look.
2. Removed unnecessary CSS.
3. Text alignment of list-items to left for an aesthetic look.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

Please assign the issue to me. 
@Its-Aman-Yadav

**Comment by Its-Aman-Yadav** [comment]
Sure @darshjnn

**Comment by darshjnn** [comment]
Please give label to the issue
@Its-Aman-Yadav
