### ISSUE TITLE
Email  and Submit button are not visible

### ISSUE THREAD

**Issue by Pranjalidhale0711** [Its-Aman-Yadav/Community-Site#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
The email input field and submit button are not visible on the Home page of the website. This issue prevents users from entering their email and submitting the form, which impacts the functionality and user experience.

Steps to Reproduce:

Navigate to the Home.
Observe the form where the email input and submit button should be.
Notice that both the email input field and submit button are missing or not visible.
Expected Result:
The email input field and submit button should be visible  to users.

Actual Result:
Both the email input field and the submit button are not visible.

<img width="289" alt="Screenshot 2024-05-20 at 7 08 08 PM" src="https://github.com/Its-Aman-Yadav/Community-Site/assets/123875758/9a5b74f9-086d-445b-b6a8-0abc75b9fcb1">

Please give this issue to me.I will solve it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Deepthi-Ramineni** [comment]
Can you please assign it to me...??
