### ISSUE TITLE
BUG: I want to update twitter's logo

### ISSUE THREAD

**Issue by bhumika-1127** [Its-Aman-Yadav/Community-Site#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Its-Aman-Yadav kindly assign me this issue.
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/137604220/c50e3e5b-f3b5-44cf-b4a9-9f8d284aa67b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by newcodergit** [comment]
I want to work on this issue. Please assign me this.

**Comment by Aag2004** [comment]
@Its-Aman-Yadav kindly assign me this under @gssoc'24

**Comment by nishitasinghhh** [comment]
@Its-Aman-Yadav kindly assign me this issue

**Comment by bhumika-1127** [comment]
@Its-Aman-Yadav Kindly let me know if I could help you regarding the same
