### ISSUE TITLE
Disturbed alignment of home page

### ISSUE THREAD

**Issue by bhumika-1127** [Its-Aman-Yadav/Community-Site#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Its-Aman-Yadav Assign me this task under GSSOC'24.
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/137604220/fbb63fbd-2fbd-4075-af98-89bfbc35b5aa)
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/137604220/bf8b3cc1-1743-416f-b1de-d8b8ccb95dd2)
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/137604220/6cb5d6ca-1f72-4afd-a1dd-c5d4ec34e859)
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/137604220/ec316ba8-4666-4c72-86df-157d2933e371)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct. I'm a GSSOC'24 contributor. I want to work on this issue. I want fix this issue i can solve the all alignment issue in the website.
