### ISSUE TITLE
IMPROVING FORM DESIGN

### ISSUE THREAD

**Issue by YooAshu** [Its-Aman-Yadav/Community-Site#36]
**Additional context**
improving the form design will make it look more pleasing and user friendly, currently the form is not that visible

**Comment by YazhiniVenkatesan12** [comment]
Hi, I'm yazhini , a participant in GSSoC24. I would like to contribute to this project. I have experience with HTML,CSS,JAVASCRIPT and I'm interested in improving the form design. May I be assigned to the task?

Thank you!

**Comment by debasmi** [comment]
i would want to work on this issue i am certified from coursera in front end web dev

**Comment by Vrajjangid5** [comment]
Assign this issue to me under GSSOC 2024.

**Comment by Its-Aman-Yadav** [comment]
Hey @YooAshu please work upon it

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.
