### ISSUE TITLE
[Enhancement] Modify the navbar

### ISSUE THREAD

**Issue by sau-mili** [Its-Aman-Yadav/Community-Site#378]
I wish to modify the navbar design to a properly visible nice looking navbar. Please assign me this

**Comment by KomalSrivastava** [comment]
@Its-Aman-Yadav Sir I want to work on this project could you please kindly assign me this project. I really have a great idea to modify the navbar design my aim is to redesign the navbar to create a visually appealing and prominently visible navigation bar that enhances the overall user experience.

**Comment by ravijat2026** [comment]
Hello @Its-Aman-Yadav Sir Please assign me this task . I wish to modify the navbar design and also make navbar responsive.

**Comment by Sara1428** [comment]
@Its-Aman-Yadav Please assign this issue to me, I too want to work on this.

**Comment by divyadaya** [comment]
@Its-Aman-Yadav can you please assign this task to me

**Comment by sau-mili** [comment]
@Its-Aman-Yadav please assign me this

**Comment by kkhushie** [comment]
I noticed the navbar could benefit from a design refresh. I'm confident I can create a visually clear and engaging navbar. Would you be open to assigning this to me @Its-Aman-Yadav?

**Comment by Its-Aman-Yadav** [comment]
Sure @sau-mili work on this

**Comment by Nehasree08** [comment]
hey , can you assign me to enhance and modify the nav bar
