### ISSUE TITLE
Enhance UI: Minimize Scroll Bar for Improved Aesthetics

### ISSUE THREAD

**Issue by Pratik2401** [Its-Aman-Yadav/Community-Site#38]
The current presence of a visible scroll bar is detracting from the overall aesthetics of the website. I suggest minimizing or styling the scroll bar to improve the website's visual appeal. Assigning this task to me for GSSoC contribution would enable me to enhance the UI by addressing this issue effectively

**Comment by Its-Aman-Yadav** [comment]
hey @Pratik2401 yeah sure you can work upon it

**Comment by Pratik2401** [comment]
As I was working on these current issue. I noticed that the send message in get in touch section works even if the information is empty so can I add the issue to exsiting or create a new one
