### ISSUE TITLE
BUG: Text not visible in discord and linkedin buttons

### ISSUE THREAD

**Issue by Saimanjari777** [Its-Aman-Yadav/Community-Site#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text is not visible in the discord and linkedin buttons on the homepage which I want to rectify.
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/130165687/17db74c5-f7d6-443f-bcb1-01e1d8f297ff)
I am working under GSSoC'24
Please assign this task to me @i

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Thank you @Saimanjari777  please work on it

**Comment by avilash01** [comment]
Can you please assign this task to me ?
