### ISSUE TITLE
 Add Discord Icon in the Join discord sections 

### ISSUE THREAD

**Issue by Sibam-Paul** [Its-Aman-Yadav/Community-Site#40]
**Is your feature request related to a problem? Please describe.**
No icon of Discord in the Join Discord button

**Describe the solution you'd like**
I can add the Discord icon in the discord button and make the button look nice and successfully navigate to discord after adding the icon

**Additional context**
![Screenshot 2024-05-10 223745](https://github.com/Its-Aman-Yadav/Community-Site/assets/158052549/8196a8b1-fd95-4ec4-8d40-f510f0a52f69)
![Screenshot 2024-05-10 223828](https://github.com/Its-Aman-Yadav/Community-Site/assets/158052549/15cecc47-1cdf-4642-995b-d5f68d5259ee)

@Its-Aman-Yadav Hey Please do ***assign*** me this , so that I can work on this under GSSOC'24 and give necessary tags

**Comment by RS-labhub** [comment]
Assign me this issue

**Comment by anshmanitripathi** [comment]
Assign this issue to me under GSSOC 2024.

**Comment by Vrajjangid5** [comment]
Assign this issue to me under GSSOC 2024.

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24 @Its-Aman-Yadav .

**Comment by lodhivishalcoder28** [comment]
@Its-Aman-Yadav Please assign me this issue under GSSoC'24

**Comment by Its-Aman-Yadav** [comment]
Duplicate Issue, please raise another

**Comment by varshith257** [comment]
@Its-Aman-Yadav  I am from the GSSOC community.  Please assign the issue on a First Come First Serve Basis. And add labels for the issue. I am reverting this PR as it has not assigned the issue to anyone and got merged the PR. It's negatively impact the community

**Comment by varshith257** [comment]
Reopen it

**Comment by Sibam-Paul** [comment]
@Its-Aman-Yadav I was the first to report this . So please assign it to me. 
Its unfair and bad and imposing negative impact to community GSSOC'24  guidelines

CC @Sibam-Paul
