### ISSUE TITLE
Feat: Left and right scrolling effect on testimonals

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#401]
### Describe the feature

Hey @Its-Aman-Yadav 
I will also add a few more reviews.
I want to add left and right CSS scrolling effect to testimonals.

Please assign me.
Thank you!

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/ebf3e7c8-bdbb-496c-b97a-d8b6594a845a)

I want to add this effect.

https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/aab86c99-4fff-43f8-b864-7562c185d3e7

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Sure @Hemav009
