### ISSUE TITLE
Feat: a personalised chatbot for the website

### ISSUE THREAD

**Issue by kairveeehh** [Its-Aman-Yadav/Community-Site#404]
### Describe the feature

a small icon that appears on the side as the site loads , and can let users know about the website and features more , can also act as a guide and pop up to join discord as well 
@Its-Aman-Yadav 
### Add ScreenShots

it will be a new feature

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
It is already completed
