### ISSUE TITLE
placing open learning, network and mentorship in cards and make them visually appealing when we hover on them

### ISSUE THREAD

**Issue by ASLSwetha** [Its-Aman-Yadav/Community-Site#41]
**Describe the bug**
placing open learning, network and mentorship in cards and make them visually appealing when we hover on them. I can definitely help with that!

**Comment by motuncoded** [comment]
Can I work on this issue?

**Comment by Its-Aman-Yadav** [comment]
Sure, work on this assigning to you @ASLSwetha

**Comment by drick-infinity** [comment]
I did this plz check issue #12

**Comment by drick-infinity** [comment]
hover effect is updated
