### ISSUE TITLE
BUG: ChatBot button's background

### ISSUE THREAD

**Issue by Aarzookhunger** [Its-Aman-Yadav/Community-Site#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/116306749/59614123-0f15-4df2-9922-a62892d644c3)

In the chatBot button in the right there appears unusual white square behind which should be removed.

Kindly assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Thank you @Aarzookhunger

**Comment by Aarzookhunger** [comment]
@Its-Aman-Yadav 
The scroll-to-top feature and the chatbot feature are conflicting here.
Like the scroll-to-top gets hidden behind the chatbot button and the white background is of scroll-to-top.

Now since chatbot is much important functionality do you want me to remove the scroll-to-top feature as anyways it's not being used here?

Kindly direct me towards how should I proceed with this one?

**Comment by Aarzookhunger** [comment]
@Its-Aman-Yadav 
Kindly reply so that I can work on the issue..!

**Comment by Its-Aman-Yadav** [comment]
Hey @Aarzookhunger yup, please replace it with the chat bot 

Thank you

**Comment by Aarzookhunger** [comment]
> Hey @Aarzookhunger yup, please replace it with the chat bot
> 
> Thank you

I've done the changes and created a pull request. U may review thankss!
