### ISSUE TITLE
Quick links

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#419]
### Describe the feature

would like to add quick links to about us and contact us
By clicking the quick link page will move to that section.

please assign me.
Thank you.

### Add ScreenShots

![Screenshot 2024-05-21 161538](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/f85d1e49-a464-4f2b-8766-82358ac09bb6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Thank you @Hemav009
