### ISSUE TITLE
Form validation issue

### ISSUE THREAD

**Issue by ASLSwetha** [Its-Aman-Yadav/Community-Site#42]
**Describe the bug**
I noticed the issue with the form validation, before sending message we have to conform whether all the details in the form are filled or not. I can definitely help with that!

**Comment by pandey079** [comment]
Please assign it to me

**Comment by Vrajjangid5** [comment]
please assign to me under GSSOC'24

**Comment by thunders123** [comment]
I would like to work on this project . please assign it to me.

**Comment by Its-Aman-Yadav** [comment]
It is under work in another PR, please raise another issue to work upon
