### ISSUE TITLE
Feat: Want to add discord icon in the join discord button

### ISSUE THREAD

**Issue by Sibam-Paul** [Its-Aman-Yadav/Community-Site#436]
### Describe the feature

want to add discord icon  in the join discord button

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/158052549/11c56494-6df0-464e-8aee-f88c21eb5789)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sibam-Paul** [comment]
please assign me this under gssoc'24

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and would love to contribute. Can you please assign me this issue.
