### ISSUE TITLE
Feat: Implement length for message in Contact Us form

### ISSUE THREAD

**Issue by Aarzookhunger** [Its-Aman-Yadav/Community-Site#446]
### Describe the feature

In the contact us form, a check over message length should be there such as length of message should be greater than 100.
It'll help to avoid receiving empty 1-2 character messages which others may send without any purpose.

This may help in decluttering the message piles being received.

Also the UI of the form can be improved by adding box-shadow on hovers, border enhancements etc.

Kindly assign this issue to me under GSSOC'24!
Thanks..

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/116306749/36825fcf-bc5d-4108-b1e1-e618a74a87db)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
Sure @Aarzookhunger
