### ISSUE TITLE
Feat: Add back to top button

### ISSUE THREAD

**Issue by Saimanjari777** [Its-Aman-Yadav/Community-Site#450]
### Describe the feature

The back to top button is missing. The back to top button increases the user navigation easy.
I would like to work on this issue
Please assign this issue to me @it

### Add ScreenShots

![Screenshot 2024-05-21 201417](https://github.com/Its-Aman-Yadav/Community-Site/assets/130165687/70ad0cfb-2b8e-44d7-a790-a3f7c3c09c82)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalivarapubindusree** [comment]
It was already there @Saimanjari777
