### ISSUE TITLE
Page UI can be improved.

### ISSUE THREAD

**Issue by anshmanitripathi** [Its-Aman-Yadav/Community-Site#46]
Page UI can be impoved.

**Comment by anshmanitripathi** [comment]
I want to work Upon this assign this task to me.

**Comment by Its-Aman-Yadav** [comment]
Raise a PR for that
Thank you

**Comment by richasriva** [comment]
Hi, I can fix this issue properly, kindly assign this task to me.

**Comment by anshmanitripathi** [comment]
Level as GSSOC 24 and level 1. i had done with the changes i am going to push it.

**Comment by MehtabAsHellic** [comment]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab
