### ISSUE TITLE
BUG: Adding Hovering effect to submit button

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Its-Aman-Yadav/Community-Site#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/153417476/d9e3eb64-f259-4755-9a4a-2202b2bbfeca)
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/153417476/69ffb008-a668-4799-a3f9-03a8e333e382)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Henin-6024** [comment]
I would like to resolve this issue. Kindly assign this task to me with required GSSOC'24 Labels
