### ISSUE TITLE
BUG:Feedback button not opening

### ISSUE THREAD

**Issue by ayushkrrana** [Its-Aman-Yadav/Community-Site#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we clicked on the feedback button , the button is not working
please assign it to me @Its-Aman-Yadav 
Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ananya-Nair20** [comment]
Hello @Its-Aman-Yadav 

I am participating in GSSOC'24. I am interested in resolving this issue. Please assign this issue to me under GSSOC'24 with appropriate level labels.

Thank you
