### ISSUE TITLE
Feat: Addition of links to footer 

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#533]
### Describe the feature

I want to add links to footer items.(company)
By clicking the quick link, the page will move to that section.

### Add ScreenShots

![Screenshot 2024-06-01 210515](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/d148aebe-d3ae-4675-8f41-426389bcac3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meayushsriv** [comment]
Please assign me the issue, so I can start working on this repo. @Its-Aman-Yadav
Thank you!

**Comment by gaurav9117** [comment]
Please assign me the issue.
