### ISSUE TITLE
BUG: Contact Form Issues and enhancement request

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [Its-Aman-Yadav/Community-Site#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am writing to report a few issues with the contact form on our website and to suggest an enhancement for improved user experience.

<h3>Issues:</h3>
Invisible Typed Message: When users type a message in the contact form, the text is not visible.
Invisible Icons: The icons on each field of the contact form are not displaying.

<h3>Enhancement Request:</h3>
Immediate Feedback Alert: Adding an alert that says "Your message has been sent" will provide users with immediate feedback, enhancing their trust and reliability in our website.

<br>

![gssoc12](https://github.com/Its-Aman-Yadav/Community-Site/assets/128472306/9e830266-ae57-43de-af29-3f98f31b4128)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ayesha-Siddiqua88** [comment]
@Its-Aman-Yadav please assign this issue to me under gssoc

**Comment by Its-Aman-Yadav** [comment]
Sure @Ayesha-Siddiqua88
