### ISSUE TITLE
BUG: Text is not visible

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Its-Aman-Yadav/Community-Site#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-02 132253](https://github.com/Its-Aman-Yadav/Community-Site/assets/153417476/c71b54ae-2782-4849-84c0-06242067ffd7)

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/153417476/328a1988-c235-4431-932e-aadceff2d250)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AfrozeSVU** [comment]
@Its-Aman-Yadav please assign me this issue

**Comment by SanjanaSuryadevara** [comment]
@Its-Aman-Yadav please assign this issue to me
