### ISSUE TITLE
BUG: Height of footer is too much

### ISSUE THREAD

**Issue by gyanshankar1708** [Its-Aman-Yadav/Community-Site#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/155980409/c09a8bc1-60ae-40cb-adf3-4017688ce077)
Height of the footer section is too much.  The negative space is too much.
I want to work on this issue. Please assign me under GSSOC.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meayushsriv** [comment]
@Its-Aman-Yadav please assign this issue to me under gssoc'24.

**Comment by mehrun171** [comment]
@Its-Aman-Yadav i would like to work on this issue..please assign me

**Comment by gyanshankar1708** [comment]
I had raised pull request of this issue.
PR #631 
please review it and close this issue.

**Comment by Aarushi232005** [comment]
@Its-Aman-Yadav please assign this issue to me under gssoc'24.

**Comment by gyanshankar1708** [comment]
@Its-Aman-Yadav, Hence the issue is resolved and merged.
So, please close the issue.
