### ISSUE TITLE
BUG: Some Issues in the interface

### ISSUE THREAD

**Issue by debangi29** [Its-Aman-Yadav/Community-Site#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# There is some problem in the HTML code
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/117537653/2f480080-c9f7-47b2-8d94-583b37d8b583)

# 2. Problem in FAQ section
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/117537653/4cc33d73-f70e-4fe6-84c3-82e819642679)

# 3.  The testimonials have all the photos removed only 3 of them revolves; Background doesn't look good. Background must be added ; Arrows not visible

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/117537653/2f006c08-26b5-44c9-84f3-6d73d248128f)

# 4. Service cards not of same size
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/117537653/b7791c6a-2525-4225-8d3d-2794771ec401)

# 5. Feedback and contact section UI needs to be improved

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Praneeth-2602** [comment]
Why is this issue still open 👀
