### ISSUE TITLE
[ Feature ]  Add Navbar

### ISSUE THREAD

**Issue by Its-Aman-Yadav** [Its-Aman-Yadav/Community-Site#6]
Add Navbar at the top of the page which sticks through out the website

**Comment by rishyym0927** [comment]
Hi @Its-Aman-Yadav 

I'd like to take ownership of the task to "Add Navbar at the top of the page which sticks throughout the website." I'm confident I can implement the required navbar with sticky behavior effectively.

Looking forward to your response.

Best regards,

**Comment by udita-0707** [comment]
Hi @Its-Aman-Yadav ,

I hope this message finds you well. I'm reaching out to express my interest in contributing to the project and to request assignment of this issue titled "Add Navbar at the top of the page which sticks throughout the website."

I've reviewed the issue description and I believe I can make a meaningful contribution to address it.  Please let me know if this issue is available for assignment. 

Looking forward to contributing to the project!

Best regards,

**Comment by AkshitGarg24** [comment]
Hi @Its-Aman-Yadav,

I'm eager to tackle the "Add Navbar" issue. Could you please assign this task to me?

Looking forward to your response.

Best regards,

**Comment by Jithendranath8** [comment]
Hi @Its-Aman-Yadav, i have experience in adding nav bar in responsive way , i think i can solve this issue . Please assign this issue to me

**Comment by vaishnavip27** [comment]
Hey @Its-Aman-Yadav i would love to work on this issue. As a developer keenly interested in designing too.. i think I can work on this issue. Can you assign it to me? Looking forward for the approval

**Comment by shreyyq** [comment]
Hi @Its-Aman-Yadav i would like to work on this issue and fix it, please assign this issue to me.

**Comment by kamalesh-og** [comment]
Hi @Its-Aman-Yadav, I would like to work on this "navbar" section. 
Can you assign it to me?
Thank You.

**Comment by shuhaki** [comment]
hey@Its-Aman-Yadav  i would love to work on this issue.i have very good experience in fronted part, i did some good projects related to this issue so, could you please assaign it to me i will do it

**Comment by negia7014** [comment]
hey@Its-Aman-Yadav  I'm eager to tackle the "Add Navbar" issue. could you please assign this issue to me . i will do it

**Comment by AbhinaySngh** [comment]
Hi @Its-Aman-Yadav I want you to let me tackle the "Add Navbar" issue and i assure you that you will be happy with my work.

**Comment by singhrimiumesh** [comment]
hello @Its-Aman-Yadav , I'm eager to add a navbar to the website to enhance navigation and user experience. The navbar will provide easy access to important sections of the site, such as joining the community on Discord and learning about our mission. I'll ensure the navbar is responsive and integrates seamlessly with the existing design.

**Comment by aanchalpahuja18** [comment]
Hello @Its-Aman-Yadav, I would like to contribute in this issue and fix this so that the nav bar looks super cool. I have experience in Making these things look aesthetic and appealing. So kindly accept my contribution request

**Comment by iamkanhaiyakumar** [comment]
Hey @Its-Aman-Yadav 
I hope this message finds you well. I'm eager to collaborate on enhancing the Nav-Bar's UI and making it visually appealing.

I'd appreciate it if you could review my GitHub profile to see some of my previous work and design projects. I believe my experience in creating aesthetic designs could be valuable for this task.

Thanks

**Comment by toastmaster-Pritam** [comment]
Hey @Its-Aman-Yadav  I would like to work on feature #9 Adding a sticky Navbar ,also can make its UI visually appealing.
I would like to request you to assign me the task.

Thanks

**Comment by Lavanyaaa25** [comment]
Hi @Its-Aman-Yadav,
I'm reaching out to express my genuine interest in contributing to the project and to request assignment of the issue titled **"Add Navbar #6"**
After carefully reviewing the issue description, I'm excited about the opportunity to tackle this challenge. I have experience implementing sticky navigation bars and am confident in my ability to deliver a solution that aligns with the project's goals and requirements.
I'm eager to dive into this task and collaborate with the team to enhance the website's user experience. Assigning this issue to me would not only allow me to showcase my skills but also contribute to the project's success.

Thank you.

**Comment by Its-Aman-Yadav** [comment]
Hey @singhrimiumesh I am assigning this issue to you, please work on it
Thank you

**Comment by singhrimiumesh** [comment]
Thank you for assigning me the task, @Its-Aman-Yadav !

**Comment by vansh-attri** [comment]
Hi @Its-Aman-Yadav , If anyone is not working on this. Can you please assign it to me?

**Comment by harinisayani** [comment]
Hi @Its-Aman-Yadav , I have good experience in adding navbar. I want to contribute to this feature. Would you please assign me this task?

**Comment by harikasayani** [comment]
Hi @Its-Aman-Yadav 
Could you please assign "Add Navbar #6" task to me. I want to contribute it.

**Comment by Abdal192003** [comment]
Hi @Its-Aman-Yadav ,
Could please assign this issue to me under gssoc'24 , will try my best to solve this issue
Thanks

**Comment by SuhainaFathimaM** [comment]
Hi @Its-Aman-Yadav

I'd like to take ownership of the task to "Add Navbar at the top of the page which sticks throughout the website." I'm confident I can implement the required navbar that sticks through out the website

Looking forward to your response.

Best regards,

**Comment by palayushi293** [comment]
Hi @Its-Aman-Yadav 

I want to take the ownership of this project "Add navbar" I am confident to do this .
Looking forward to your response .
Best regards,

**Comment by shendgeshraddha** [comment]
Subject: Issue Assignment Request - Adding Navbar

I hope you're doing well. I'd like to propose adding a navbar to our website for consistent navigation across all pages. This enhancement would greatly improve user experience and streamline access to key sections. Could you please assign me this issue? I'm eager to solve the issue and ensure a seamless integration throughout the site.

**Comment by shendgeshraddha** [comment]
Could you please assign me this issue??
