### ISSUE TITLE
Feat: Adding form validation in login and signup page

### ISSUE THREAD

**Issue by Ketanop321** [Its-Aman-Yadav/Community-Site#611]
### Describe the feature

When someone will enter wrong email or password it will show warning
Here is example how will it look

### Add ScreenShots

![Screenshot 2024-06-04 215349](https://github.com/Its-Aman-Yadav/Community-Site/assets/146806880/d89374cc-e830-4c59-9d99-15f0c31f748c)
![Screenshot 2024-06-04 223248](https://github.com/Its-Aman-Yadav/Community-Site/assets/146806880/78230d8f-86e0-485a-acd5-a7939e635763)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Tanishka023** [comment]
Hey @coderiksenthil   Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.

Regards,
Tanishka Bhalla

**Comment by Ketanop321** [comment]
> Hey @coderiksenthil   Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.
> 
> Regards, Tanishka Bhalla

i had already solved the issue and it also got merged

**Comment by Tanishka023** [comment]
> > Hey @coderiksenthil   Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.
> > 
> > Regards, Tanishka Bhalla
> 
> i had already solved the issue and it also got merged

Ohh!! There was nothing mentioned, so I commented on this issue to be assigned.

**Comment by coderiksenthil** [comment]
> > > Hey @coderiksenthil   Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.
> > > Regards, Tanishka Bhalla
> > 
> > 
> > i had already solved the issue and it also got merged
> 
> Ohh!! There was nothing mentioned, so I commented on this issue to be assigned.

Actually, I am not the Project Admin Please tag the respective Project Admin @Tanishka023 @Ketanop321
