### ISSUE TITLE
Addition of nav bar to about page

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#614]
### Describe the feature

I would like to add nav bar to about page

Please assign me and merge the pull request.

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/98fe938a-65c2-46c7-850f-cc6bff942bb4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
please assign to me under Gssoc 2024
