### ISSUE TITLE
BUG: Text overflow while hovering

### ISSUE THREAD

**Issue by HritikaPh** [Its-Aman-Yadav/Community-Site#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/104688406/d1539ce0-5870-4d0b-bf84-feacd0c667f1)

When hovering over the cards in the FAQs section, the text spills out of the box. Additionally, the 5th star on the 3rd card is missing. Please assign this task to me under GSSoC and apply the appropriate labels. 
Thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HritikaPh** [comment]
@Kalivarapubindusree please assign me this issue under gssoc.

**Comment by Kalivarapubindusree** [comment]
Mention ur pr here @HritikaPh

**Comment by Gokilp** [comment]
Please assign to me

**Comment by Kalivarapubindusree** [comment]
Please raise an issue separately @Gokilp

**Comment by Gokilp** [comment]
Thank you so much

**Comment by HritikaPh** [comment]
@Kalivarapubindusree, refer to [PR #617](https://github.com/Its-Aman-Yadav/Community-Site/pull/617) for more information.
