### ISSUE TITLE
Feat: Redesigning the FAQs section

### ISSUE THREAD

**Issue by ayush-848** [Its-Aman-Yadav/Community-Site#643]
### Describe the feature

I will redesign this part with more effects, colors and transistions

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/126975547/eb1d2d34-c366-4df8-8801-5a12bb613e5c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@Kalivarapubindusree please assign this issue to me

**Comment by Kalivarapubindusree** [comment]
Please add the extra questions below the FAQs  in the FAQs section.merge all the questions in a good format @ayush-848

**Comment by ayush-848** [comment]
@Kalivarapubindusree can you give me some suggestions about the questions

**Comment by Kalivarapubindusree** [comment]
![Screenshot_2024-06-07-14-04-43-33_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Its-Aman-Yadav/Community-Site/assets/114821855/ace39811-8c1b-4752-83c0-53c7bb86eb4a)
See in this pic there are some questions present out of the FAQs section plse keep those questions also in FAQs section

**Comment by ayush-848** [comment]
> ![Screenshot_2024-06-07-14-04-43-33_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/114821855/337587145-ace39811-8c1b-4752-83c0-53c7bb86eb4a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDk3MzcsIm5iZiI6MTcxNzc0OTQzNywicGF0aCI6Ii8xMTQ4MjE4NTUvMzM3NTg3MTQ1LWFjZTM5ODExLThjMWItNDc1Mi04M2MwLTUzYzdiYjg2ZWI0YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QwODM3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmEyNTQxZGI2NzU1YTVlOTdlZDA4NjVkYjY5MzZiYmU5ZGUyYjE2ODU3NmQxMDYxOTdlNDIyNjc3ZTM5MjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XfiBZoFq1F27KDyeq_UlBgIVbT9NIi0oD5p51k2MvpI) See in this pic there are some questions present out of the FAQs section plse keep those questions also in FAQs section

Oh understood 
I will do it
