### ISSUE TITLE
BUG: In footer Email input section when we sent page reloads

### ISSUE THREAD

**Issue by zalabhavy** [Its-Aman-Yadav/Community-Site#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In footer's Email input field when we fill email and click on sent icon page reload i will stop that and show message Thank you !.
I will use java-script to solve that.

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/126322584/5bb19552-afd0-412f-b368-92c689d95706)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently Footer page has not such a good style .

*Describe the solution you'd like*
Adding margin, padding and set allginment and change in font and changes according to Footer

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me
