### ISSUE TITLE
copyright year_BUG:

### ISSUE THREAD

**Issue by Meetjain1** [Its-Aman-Yadav/Community-Site#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

copyright year is not there currently in our website , I see many tried to work on this but not able to fix it , I will write a code in it to fetch dynamically the current year for copyright rather than copy pasting the year using html.
@Its-Aman-Yadav assign this issue to me I will fix it 
![village ](https://github.com/Its-Aman-Yadav/Community-Site/assets/133582566/1666befa-a1de-40d8-96ab-718585b10331)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi-Gopinath** [comment]
Kindly assign me this issue under GSSoC'24. I would like to work on it @Its-Aman-Yadav

**Comment by Meetjain1** [comment]
@Kalivarapubindusree have a look on this issue and assign me . Thanks
