### ISSUE TITLE
Feat: Design New Feedback and Contact Form

### ISSUE THREAD

**Issue by zalabhavy** [Its-Aman-Yadav/Community-Site#675]
### Describe the feature

This present forms not looks good.
I will give them more attractive look.
Also Use JS for assure that messages sent that give better experience to user.

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/126322584/bb882857-93f4-4bb2-8f4e-896cde81fcdb)

I will create better UI than this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalivarapubindusree** [comment]
I will add level after u make pr @zalabhavy

**Comment by zalabhavy** [comment]
@Kalivarapubindusree Ok no problem !
