### ISSUE TITLE
BUG: "About" Section Overlapping "Services" Section

### ISSUE THREAD

**Issue by SahilThakur02** [Its-Aman-Yadav/Community-Site#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "About" section is visually overlapping the "Services" section. This creates a misalignment on the page. If observed carefully, the section can be seen intruding into the "Services" section aswell on browser.

<img width="466" alt="Screenshot 2024-06-09 091100" src="https://github.com/Its-Aman-Yadav/Community-Site/assets/112742544/0f79cb22-0503-4226-bf91-f2db0b207307">

**Should look like this insead:**
<img width="399" alt="Screenshot 2024-06-09 091641" src="https://github.com/Its-Aman-Yadav/Community-Site/assets/112742544/8c60a434-28bd-4df6-bbdb-dc4b82ad0d03">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SahilThakur02** [comment]
Please /assign me this issue 
@Kalivarapubindusree

**Comment by Its-Aman-Yadav** [comment]
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/97724135/e8fc22d8-496d-4cef-bbed-fce773dd3798)
It is fine btw

**Comment by SahilThakur02** [comment]
Looks like someone's PR fixed it.
