### ISSUE TITLE
Creating signup page for open source villager.

### ISSUE THREAD

**Issue by sonarani1** [Its-Aman-Yadav/Community-Site#69]
Hi, I want to create a signup page for your project. Kindly assign this work to me under GSSOC'24. I can do it properly.

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Roy-Soumik** [comment]
hello, I am a gssoc 2024 contributer, could you please assign this task to me, please add the gssoc 2024 label
