### ISSUE TITLE
No "Header and Footer" In Login Page

### ISSUE THREAD

**Issue by Its-your-rj** [Its-Aman-Yadav/Community-Site#691]
### Describe the feature

Login page in the website doesn't contain header and footer please assign me a task to add the same.

### Add ScreenShots

<img width="960" alt="Screenshot 2024-06-09 153429" src="https://github.com/Its-Aman-Yadav/Community-Site/assets/131703345/8bf51645-a36a-469e-bc0f-794318f1a369">
The above page doesnt contain header or footer please assign me this task under GSS0C'24 with the label of level 3. It will help me a lot .
Thanking you
Raj Mehta

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Its-Aman-Yadav** [comment]
I don't think so there is a need of header and footer here @Its-your-rj
