### ISSUE TITLE
Changing font color throughout the website.

### ISSUE THREAD

**Issue by sonarani1** [Its-Aman-Yadav/Community-Site#70]
Hi, I want to change the font color throughout the website to make it effective and eye-catching. Kindly, assign this work to me under GSSOC'24.

**Comment by Sambit-Mondal** [comment]
With my skills adn deep knowledge related to proper designing and colour combinations, I can work on this issue more effectively.
Please assign this issue to me under GSSoC '24.

Thank you!

**Comment by dubeyadarsh862** [comment]
please assign me this issue under GSSoC'24

**Comment by Its-Aman-Yadav** [comment]
hey @sonarani1 kindly work upon it

**Comment by princyym** [comment]
hello I want to work on it can you assign it to me @sonarani1

**Comment by Roy-Soumik** [comment]
hello, I am a gssoc 2024 contributer, could you please assign this task to me, please add the gssoc 2024 label

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by ashish027120** [comment]
Can you please assign me this issue , I want to work on this

**Comment by sonarani1** [comment]
Issue solved.
