### ISSUE TITLE
Feature : Hovering for the testimonials

### ISSUE THREAD

**Issue by GAVINESHWAR** [Its-Aman-Yadav/Community-Site#708]
### Describe the feature

Adding the hover features to the testimonials , making attractive while hovering and adding cursor pointer for reviews 

### Add ScreenShots

before 
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/124431955/f745b69e-3512-4414-b07c-38bd65f1d612)

After 
![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/124431955/80baaa93-a93c-46cc-b0af-6795dc9e4ebf)

Assign me this issue @Its-Aman-Yadav  to work on it 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GAVINESHWAR** [comment]
Assign me this issue  @Kalivarapubindusree    to make hovering effect to testimonials

**Comment by GAVINESHWAR** [comment]
I PR the issue and it was merged Thank you for accepting @Kalivarapubindusree

**Comment by Kalivarapubindusree** [comment]
Do more contributions to this project. @GAVINESHWAR
