### ISSUE TITLE
social media redirection issue

### ISSUE THREAD

**Issue by creativeadi** [Its-Aman-Yadav/Community-Site#71]
Describe the bug
On clicking the social media handle, there is no redirection to the social media handle of this community.

https://github.com/Its-Aman-Yadav/Community-Site/assets/153895524/783c3af6-2035-4b5a-b178-2607b5c5d69d

**Expected behavior**
on clicking the social media handles, the click should redirect the user to the community's social media pages.

**Comment by creativeadi** [comment]
@Its-Aman-Yadav  kindly provide me the twitter and ig handle of this community, so that i can try solving the above issue

**Comment by Saloni-0465** [comment]
Issue: Implementing Social Media Handle Redirection

Proposed Solution:

1. Integrate correct URLs for each social media handle.
2. Implement "_blank" target attribute for opening links in new tabs.
3. Ensure accessibility by providing descriptive link text.

Could you please provide me with the official social media handles this community and assign the issue to me .
@Its-Aman-Yadav

**Comment by Its-Aman-Yadav** [comment]
already resolved
Thank you
