### ISSUE TITLE
BUG: Text border

### ISSUE THREAD

**Issue by dishathakurata** [Its-Aman-Yadav/Community-Site#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The homepage text is getting merged with the background picture. I want to add border around the text so that it can be visible with any background picture.
![border](https://github.com/Its-Aman-Yadav/Community-Site/assets/146114938/1a4acca1-7478-4e6f-9841-d0a7eb7c064e)

Assign this issue to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by geeta052** [comment]
hello @Its-Aman-Yadav 
please assign this issue to me?

**Comment by geeta052** [comment]
please assign this issue to me?

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by HareRamDwivedi** [comment]
Please assign me this issue under GSSoC'24

**Comment by SohamDas00** [comment]
pls assign this issue
