### ISSUE TITLE
Feat: Add Stylish Scrollbar

### ISSUE THREAD

**Issue by zalabhavy** [Its-Aman-Yadav/Community-Site#733]
### Describe the feature

This website have default scrollbar.
I will add stylish scrollbar.

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/126322584/ddbbcb4f-0f49-4da3-b637-c001acc72209)

This is demo look of new scrollbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Kalivarapubindusree @Its-Aman-Yadav Please assign me this task.

**Comment by sharathrekulara21** [comment]
I guess reducing the size of the scrollbar would help in increasing the experience for the user. please assign me this task.

**Comment by iakshkhurana** [comment]
I would like to work on this. Please assign me this issue to contribute to this project
