### ISSUE TITLE
URGENT LOOK INTO THE MERGED PRs

### ISSUE THREAD

**Issue by kairveeehh** [Its-Aman-Yadav/Community-Site#74]
@Its-Aman-Yadav  while starting to correct my issues as I opened the local repo there is a total mess on the site and even in the live link , I would urgently request you to please look into this and do something 
## please let me know if it is intentional
![Screenshot 2024-05-11 145505](https://github.com/Its-Aman-Yadav/Community-Site/assets/145572028/36469aa5-c90c-49f6-9b86-e170cd9da1e7)
![Screenshot 2024-05-11 145510](https://github.com/Its-Aman-Yadav/Community-Site/assets/145572028/18376e32-6c91-47cd-bea1-ee7da914784c)
![Uploading Screenshot 2024-05-11 145505.png…]()

![Screenshot 2024-05-11 145458](https://github.com/Its-Aman-Yadav/Community-Site/assets/145572028/fcf612cf-485c-403c-a27f-4e6744de9d24)

**Comment by Its-Aman-Yadav** [comment]
Thank you @kairveeehh for your attention, accidently merged a PR, now everything is fine
Please work on your issue
