### ISSUE TITLE
Allignment of Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [Its-Aman-Yadav/Community-Site#742]
### Describe the feature

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to Correctly Allign the Navbar items to Make Website to look Attractive
Can you please assign me this issue under gssoc'24

### Add ScreenShots

![ppp](https://github.com/Its-Aman-Yadav/Community-Site/assets/161804629/cff4a881-6905-467b-9d73-b34eedc0741e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
@Kalivarapubindusree please add level label under GSSOC'24

**Comment by Kalivarapubindusree** [comment]
I have added labels for pr and that level labels will only count to marks so no need to add level labels here in issues @sailaja-adapa

**Comment by sailaja-adapa** [comment]
yeah thankyou @Kalivarapubindusree
