### ISSUE TITLE
Feat: Add Whatsapp icon to add whatsapp community feature to the website and Email icon for mail

### ISSUE THREAD

**Issue by GAVINESHWAR** [Its-Aman-Yadav/Community-Site#748]
### Describe the feature

In the footer there is all social media links but **whatsapp community link** was not there i would like to add a whatsapp community feature to the website users can follow the whatsapp community as well. In additon to that we can add **email icon**  for the email sending purpose at the social media place.

Assign me this issue @Its-Aman-Yadav sir and @Kalivarapubindusree  mam to make contribution to the project

Thank you

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/124431955/5aaf80ac-5baf-4169-853c-7b09d7cc9dbe)

Here in this place we can add Whatsapp community icon , email id icon and discord as well not to go again top

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Poonam-Kashyap12** [comment]
I want to work on this issue, please assign it to me.

**Comment by GAVINESHWAR** [comment]
Thank you for the response sir @Its-Aman-Yadav
