### ISSUE TITLE
Feat: Improved Login page ui with animations

### ISSUE THREAD

**Issue by AbheetHacker4278** [Its-Aman-Yadav/Community-Site#775]
### Describe the feature

I have improve the login page both in signIn and signup with Animation , I have already open this PR , Kindly verify it once and merge with main [branch.]

https://github.com/Its-Aman-Yadav/Community-Site/assets/114290748/42aafce1-cef9-4695-8b78-4e94fd7e5b6e

### Add ScreenShots

**BEFORE**
![Screenshot 2024-06-16 120809](https://github.com/Its-Aman-Yadav/Community-Site/assets/114290748/07649a08-12c9-47a6-9129-7b4ac653c937)

**AFTER**
![Screenshot 2024-06-16 120834](https://github.com/Its-Aman-Yadav/Community-Site/assets/114290748/fc0021c3-7451-4bc4-9048-d4c4c974158a)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbheetHacker4278** [comment]
@Its-Aman-Yadav please check this also , and review it please

**Comment by AbheetHacker4278** [comment]
@Kalivarapubindusree  please ckeck this out

**Comment by Kalivarapubindusree** [comment]
Can you please mention the pr number here
