### ISSUE TITLE
Feat:Add Scale and more hover effects on social icons in footer.

### ISSUE THREAD

**Issue by zalabhavy** [Its-Aman-Yadav/Community-Site#779]
### Describe the feature

In this website only color changed when i hover in social icons i will add other effects like scale , shadow ect.

### Add ScreenShots

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/126322584/58037baf-79bf-4489-8998-546ff9522e53)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Kalivarapubindusree @Its-Aman-Yadav Please assign me this task.

**Comment by Kalivarapubindusree** [comment]
I think hover effect is there on social media links in the footer @zalabhavy so please try in different way and upgrade the ui

**Comment by zalabhavy** [comment]
@Kalivarapubindusree Ok
