### ISSUE TITLE
Font visibility

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#80]
**Describe the bug**

Font cant be visible to read

**To Reproduce**
1. look at webpage to find issue

**Expected behavior**

1. Text should be displayed in a readable font style, size, and color that contrasts appropriately with the background. This ensures that users can easily perceive and comprehend the text content.

**Screenshots**

![Screenshot 2024-05-11 180454](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/3c46b616-78d0-4afa-8b70-8ee77aca3e3b)

**Desktop (please complete the following information):**
 - windows
 - chrome

@Its-Aman-Yadav 
please assign this issue to me.

Thank You!

**Comment by Saloni-0465** [comment]
After going through the website I realised the font of the website is not clearly visible and has font size issues.
I would love to contribute to this issue. Kindly assign it to me.

**Comment by reshamsai150** [comment]
The font is not visible  properly making the website unattractive, good font visibility is essential in the website as it plays a crucial role I want to work on this issue kindly assign this issue to me

**Comment by Its-Aman-Yadav** [comment]
This was a technical issue, thank for considering it
