### ISSUE TITLE
Improving UI / UX

### ISSUE THREAD

**Issue by chaanakyaaM** [Its-Aman-Yadav/Community-Site#81]
**Is your feature request related to a problem? Please describe.**
i would like to make the whole landing page responsive and more user friendly.

**Describe the solution you'd like**
I would change the style of the page.

**Describe alternatives you've considered**
Making the home page more interactive.

**Additional context**
would you kindly assign this issue to me under GSSOC'24.

**Comment by Its-Aman-Yadav** [comment]
duplicate issue
