### ISSUE TITLE
Form correction(send message and form deatils structure)

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#82]
**Describe the bug**

1. Form Fields are getting overlapped.
2. Clicking the "Send Message" button without filling in the required details should trigger an error message, prompting users to complete the fields before attempting to send the message, rather than redirecting to the WhatsApp link prematurely.

**To Reproduce**
1. Go to website
3. Scroll down 

**Expected behavior**

1. Clicking "Send Message" without filling in details should prompt an error message, guiding users to complete the required fields instead of redirecting to WhatsApp prematurely.

**Screenshots**

![Screenshot 2024-05-11 180445](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/49904f63-05b1-4920-a7e2-fc3ab6a26694)

**Additional context**
@Its-Aman-Yadav 
Please assign this issue to me .

Thank You!

**Comment by Its-Aman-Yadav** [comment]
it was just some technical error, now it is sorted
