### ISSUE TITLE
BUG: Eye visibility

### ISSUE THREAD

**Issue by AkhilaSunesh** [Its-Aman-Yadav/Community-Site#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/140897461/921a27dd-4920-4bd6-979c-899419a5632d)
when the user clicks on the eye, the password should be visible.
The current functionality does the exact opposite.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalivarapubindusree** [comment]
it is working fine now
