### ISSUE TITLE
Remove Text Overlapping 

### ISSUE THREAD

**Issue by sailaja-adapa** [Its-Aman-Yadav/Community-Site#826]
### Describe the feature

Hello Project Admin
I would like to remove the text overlapping as you can see in the below image
Can you assign me this issue under GSSOC'24 @Kalivarapubindusree 

### Add ScreenShots

![IMG_20240622_111259](https://github.com/Its-Aman-Yadav/Community-Site/assets/161804629/0ae972f9-d896-444a-8f1c-5bf9f77b2c7c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalivarapubindusree** [comment]
These is no overlapping when i am running in my system

**Comment by sailaja-adapa** [comment]
Okk @Kalivarapubindusree but it seemed like that in my system as you can see in screenshot

**Comment by sailaja-adapa** [comment]
Even now it is still like that @Kalivarapubindusree see the website link
