### ISSUE TITLE
Allignment of Toastify Message 

### ISSUE THREAD

**Issue by sailaja-adapa** [Its-Aman-Yadav/Community-Site#827]
### Describe the feature

Hello Project Admin
I would like to place Toastify Message in middle of page rather an at right side of page
Can you assign me this issue under GSSOC'24 @Kalivarapubindusree 

### Add ScreenShots

![IMG_20240622_111718](https://github.com/Its-Aman-Yadav/Community-Site/assets/161804629/2f0d9f97-1f0a-4160-99df-6e1716844edb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kalivarapubindusree** [comment]
You only made the Toastify message in the right side corner so please make pr and I won't give marks to that because earlier u did pr similar to this @sailaja-adapa

**Comment by sailaja-adapa** [comment]
yeah its okk @Kalivarapubindusree when i again seen website i thought it would it be better to place the toastify message to appear in middle of page

**Comment by sailaja-adapa** [comment]
I Raised another PR Kindly go through that @Kalivarapubindusree
