### ISSUE TITLE
Adding cards for presenting  information in a clear and concise way.

### ISSUE THREAD

**Issue by Hemav009** [Its-Aman-Yadav/Community-Site#83]
**Is your feature request related to a problem? Please describe.**

Information to read easily should be represented in a neat and concise way

**Describe the solution you'd like**

I would like add cards or components to make them look professional. refer below images.

issue : 
![Screenshot 2024-05-11 182216](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/5fef3256-c994-4eca-b1a0-fac2034b9669)

Solution:
![Screenshot 2024-05-11 182404](https://github.com/Its-Aman-Yadav/Community-Site/assets/109607812/7d9e2024-d757-4cc3-9538-36f70a6fe838)

I want  to add cards like the above for (open learning, mentorship, network..).

**Additional context**

@Its-Aman-Yadav 
 please assign me 
Thank You!

**Comment by Its-Aman-Yadav** [comment]
Yeah sure, please work on it

**Comment by Manishar55** [comment]
@Its-Aman-Yadav can you assign this issue to me 
I would like to add cards to make it beautiful.

**Comment by Harshdev098** [comment]
@Its-Aman-Yadav  Can you please assign this task to me
