### ISSUE TITLE
Login and sign up pages 

### ISSUE THREAD

**Issue by Saloni-0465** [Its-Aman-Yadav/Community-Site#86]
The website currently lacks login and sign-up functionality, I would like to take on this task and contribute to the project.

@Its-Aman-Yadav Assign me the issue please.

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Please assign me this !

**Comment by ankiiitagupta** [comment]
@Its-Aman-Yadav can you assign this issue to me under GSSOC'24? I would love to work on this project's issue.

**Comment by Its-Aman-Yadav** [comment]
We don't need that feature yet
thank you
