### ISSUE TITLE
Add customised scrollbar

### ISSUE THREAD

**Issue by Sneha123-zudo** [Its-Aman-Yadav/Community-Site#87]
**Is your feature request related to a problem? Please describe.**
I want to add customised scrollbar to the website for the enhancement of the website.

**Describe the solution you'd like**
I will add the customised scrollbar

**Additional context**
Please assign me this issue under GSSOC'24.

**Comment by pankaj-2503** [comment]
Assign this issue to me @Its-Aman-Yadav  i would solve this issue as mentioned

**Comment by Its-Aman-Yadav** [comment]
duplicate issue
