### ISSUE TITLE
adding  darktheme  to enhance user expeience 

### ISSUE THREAD

**Issue by reshamsai150** [Its-Aman-Yadav/Community-Site#88]
user experience will be better if we add the dark theme to the website

**Comment by Its-Aman-Yadav** [comment]
Sure, kindly work on it

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by Abdul-momin24** [comment]
can you assign this to me i can make as button which on clicking change the whole theme to dark

**Comment by anupa-rb** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.
