### ISSUE TITLE
Improving UI of GET IN TOUCH form

### ISSUE THREAD

**Issue by AnandK-pm** [Its-Aman-Yadav/Community-Site#89]
Currently the get in touch form looks out of alignment.
Please assign me this task so that i can work on this issue , so that the website looks a bit more tidy ensuring a customer friendly experience.

(Requesting as a part of GSSoC  '24 contribution)
![Screenshot 2024-05-11 195434](https://github.com/Its-Aman-Yadav/Community-Site/assets/142206618/f4bb49e3-d3c3-46bd-84b3-02f93f91ab6c)

**Comment by Its-Aman-Yadav** [comment]
Duplicate Issue
