### ISSUE TITLE
BUG: Scroll to top button is only Present in Home page

### ISSUE THREAD

**Issue by MastanSayyad** [Its-Aman-Yadav/Community-Site#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Its-Aman-Yadav  @Kalivarapubindusree

The scroll to top button Is only present in home page and in other pages it is not present 
I would like to implement the scroll to top button same as  homepage in all other pages to maintain consistency in website 

The pages are these:

![image](https://github.com/Its-Aman-Yadav/Community-Site/assets/101971980/f02fe8d6-cf07-4c1f-8184-f9ec18717908)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
@Its-Aman-Yadav I would like to work on this issue. Kindly assign me
